services:

  web:

    build:
      context: ./docker/web

    container_name: idcard-web

    ports:
      - "8443:8080"
      - "2222:22"

    volumes:
      - .:/app

    depends_on:
      - mysql

  mysql:

    image: mysql:8.0

    container_name: idcard-mysql

    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: Hello@123
      MYSQL_DATABASE: A-HAN_Raby-db

    ports:
      - "3307:3306"