apiVersion: v1
kind: Pod

metadata:
  name: idcard-pod

spec:
  containers:

  - name: web
    image: ubuntu:24.04

  - name: mysql
    image: mysql:8

    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "Hello@123"

    - name: MYSQL_DATABASE
      value: "A-HAN_Raby-db"